#!/usr/bin/env python3
"""Split each whole-garment mask into one mask PER PIECE of the outfit.

Why this exists
---------------
`mask_blue.py` answers "which pixels are the outfit", which is what makes a
recolour safe (no face, no hands, no backdrop). But a shop customer does not
buy "the outfit": they want the shirt in sky blue and the trousers in charcoal.
So every garment the manifest lists as independently recolourable needs its own
mask, and the masks must be a PARTITION - no gap between shirt and trouser, no
double-painted overlap.

How the cut is found, in priority order
---------------------------------------
 1. ANCHOR MATTE. `template/_qc/anchor2/<ID>-<piece>.png`, generated by asking
    the image model for ONE garment as white on black (`ANCHOR_PROMPT.md`). The
    anchored piece is `matte ∩ garment_mask`; every remaining piece is
    `garment_mask & ~matte`. The partition is therefore gap-free and
    overlap-free BY CONSTRUCTION - there is no shared boundary line for the
    model to draw badly. This is the route that worked on the old masters
    where everything else failed, so it is the default.
 2. SEAM. Only used when the image actually shows a cut line: a row where the
    silhouette narrows AND at least half the row's width sits on a real strong
    horizontal edge (a belt top, a jacket hem, a waistband). Both conditions,
    because "the silhouette narrows at the waist" is true of every human body
    and proves nothing about where one garment ends.
 3. Neither? The outfit is REPORTED, not guessed. A plausible-looking wrong
    boundary is worse than a missing mask, because it ships silently and shows
    up as a half-painted trouser on the live site.

Guarantees, each CHECKED before a file is written
-------------------------------------------------
  P1 partition: union of pieces == the garment mask, exactly, both directions.
  P2 disjoint:  no pixel in two pieces. Not approximated - zero.
  P3 size:      every visible piece >= 2.5% of the garment, so nothing is a
                8k-pixel sliver that the model painted by accident.
  P4 order:     an upper piece's pixels are above a lower piece's pixels
                (centre of mass), and a "top" never starts below 45% of span.
  P5 inherit:   every piece passes the same face/skin test the whole garment
                passed - a piece cannot claim head pixels the parent lacked.
  P6 hidden:    z:0 pieces (fully behind an outer layer) get a deliberately
                EMPTY mask, so the count per outfit matches the manifest and
                the site knows to recolour them with their parent.

    python3 template/tools/mask_pieces.py                # build + validate
    python3 template/tools/mask_pieces.py --report       # what still needs a matte
    python3 template/tools/mask_pieces.py --only M1 M4   # one or two outfits
"""
import argparse
import glob
import json
import os
import sys

import numpy as np
from PIL import Image
from scipy import ndimage

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
TPL = os.path.join(ROOT, "template")
ANCHOR_DIR = os.path.join(TPL, "_qc", "anchor2")

from mask_blue import mask_for

LOWER_HINTS = ("trouser", "pant", "jean", "chinos", "dhoti", "pajama", "churidar",
               "skirt", "palazzo", "salwar", "sharara", "gharara", "niq", "bottom")
UPPER_HINTS = ("shirt", "kurta", "kurti", "jacket", "blazer", "sherwani", "waistcoat",
               "top", "polo", "tunic", "choli", "blouse", "bandhgala", "nehru")


def frame_for(o):
    p = os.path.join(TPL, o["image"])
    if not os.path.exists(p):
        alt = sorted(glob.glob(os.path.join(TPL, "base", o["id"] + "-*.jpg"))) or \
              sorted(glob.glob(os.path.join(TPL, "_qc", "new", o["id"] + "-*.png")))
        if alt:
            p = alt[0]
    return p


def load_anchor(oid, piece, shape=None):
    """The mattes come back from the image model at whatever size it rendered, while the
    garment mask is at the shipped master size. Resample with NEAREST so the matte's hard
    edge stays hard - a resampled smooth edge would blur the piece boundary.
    The threshold is generous (128) on purpose: the cut line is owned by the anchored
    piece via the parent mask, so anti-aliased pixels either side are removed by `& remain`."""
    for cand in (os.path.join(ANCHOR_DIR, f"{oid}-{piece}.png"),
                 os.path.join(ANCHOR_DIR, f"{oid}-anchor.png")):
        if os.path.exists(cand):
            im = Image.open(cand).convert("L")
            if shape is not None and im.size != (shape[1], shape[0]):
                im = im.resize((shape[1], shape[0]), Image.NEAREST)
            return np.asarray(im) > 128
    return None


def seam_rows(mask, rgb):
    """Rows inside the garment that are BOTH a silhouette narrowing and a real
    horizontal edge crossing. Returns (row, score) list, best first."""
    g = rgb.mean(2)
    edge = ndimage.maximum_filter(g, 3) - ndimage.minimum_filter(g, 3) > 30
    ys = np.nonzero(mask.any(1))[0]
    if not len(ys):
        return []
    y0, y1 = int(ys.min()), int(ys.max())
    span = max(1, y1 - y0)
    w = mask.sum(1).astype(float)
    out = []
    for y in range(y0 + int(0.28 * span), y0 + int(0.78 * span)):
        xs = np.nonzero(mask[y])[0]
        if len(xs) < 40:
            continue
        above = w[max(y0, y - int(0.06 * span)):y].max() if y > y0 else 0
        below = w[y + 1:y + int(0.06 * span) + 1].max()
        if above <= 0 or below <= 0:
            continue
        narrow = 1.0 - min(above, below) / max(above, below)
        band = edge[max(0, y - 4):y + 5, xs.min():xs.max() + 1]
        cross = float(band.max(0).mean())
        if narrow > 0.10 and cross > 0.50:
            out.append((y, 0.5 * narrow + 0.5 * cross))
    out.sort(key=lambda t: -t[1])
    return out


def largest(A, m):
    lab, n = ndimage.label(A, structure=np.ones((3, 3)))
    if n <= 1:
        return A
    sz = np.bincount(lab.ravel(), minlength=n + 1)
    return lab == (int(np.argmax(sz[1:])) + 1)


def validate(pieces, garment, rgb, o, vis_order):
    """Return a list of problems. Everything here is a real defect, not a preference."""
    probs = []
    names = list(pieces)
    union = np.zeros_like(garment)
    for nm in names:
        union |= pieces[nm]
    gap = int((garment & ~union).sum())
    stray = int((union & ~garment).sum())
    over = sum(int((union & pieces[nm]).sum()) - int(pieces[nm].sum()) for nm in names)
    # P1/P2 computed exactly: overlap = sum(areas) - union area
    area_sum = sum(int(pieces[nm].sum()) for nm in names)
    overlap_px = area_sum - int(union.sum())
    if gap > 0:
        probs.append(f"P1 {gap}px of garment owned by no piece")
    if stray > 0:
        probs.append(f"P1 {stray}px of piece outside the garment mask")
    if overlap_px > 0:
        probs.append(f"P2 {overlap_px}px owned by two pieces")
    n_vis = sum(1 for nm in vis_order if pieces[nm].sum() > 0)
    for nm in vis_order:
        a = int(pieces[nm].sum())
        if a and a < 0.025 * garment.sum():
            probs.append(f"P3 {nm} is only {a}px ({a/garment.sum()*100:.1f}% of garment)")
    # P7 an ANCHORED piece must own essentially all of the cloth, minus the pieces
    # behind it. A matte that under-claims - e.g. a kurta outlined without its own
    # sleeves - leaves those pixels unowned, and "last piece takes the remainder" then
    # silently hands them to the garment behind, so the customer's kurta comes back with
    # one blue sleeve. Areas alone cannot see this; total coverage can.
    owned = np.zeros_like(garment)
    for nm in [x for x in vis_order if x in pieces]:
        owned |= pieces[nm]
    if vis_order and pieces.get(vis_order[0]) is not None:
        anchor_area = int(pieces[vis_order[0]].sum())
        rest = sum(int(pieces[n].sum()) for n in vis_order[1:])
        cov = (anchor_area + rest) / max(1, garment.sum())
        if cov < 0.97:
            probs.append(f"P7 pieces cover only {cov*100:.1f}% of the garment - a matte under-claimed (missing sleeve?)")
        if anchor_area < 0.12 * garment.sum():
            probs.append(f"P7 anchor {vis_order[0]} owns only {anchor_area/garment.sum()*100:.1f}% - it did not outline the whole garment")

    if n_vis > 1:
        coms = {}
        for nm in vis_order:
            ys = np.nonzero(pieces[nm].any(1))[0]
            if len(ys):
                coms[nm] = float(ys.mean())
        # Ordering is NOT checked geometrically. The first version of this gate
        # required a "top" to start in the upper part of the silhouette, which is simply
        # false for layered outfits: a kurta worn under a Nehru jacket has almost all of
        # its visible cloth BELOW the jacket, and M8 was rejected for exactly that. The
        # front-to-back order is already declared in pieces.json z-values, and the
        # anchor chain enforces it structurally, so what is worth failing on instead is
        # the mistake the ordering test kept mistaking for itself - a piece that ended up
        # as crumbs because the piece in front of it over-claimed.
        last = vis_order[-1]
        la = int(pieces[last].sum())
        if la < 0.025 * garment.sum():
            probs.append(f"P4 {last} is left with only {la}px ({la/garment.sum()*100:.1f}%) - the piece in front of it ate it")
    # P6 hidden pieces must be present and exactly empty (the site recolours them with
    # their parent; a stray pixel there would paint a garment nobody can see)
    for nm in [p["piece"] for p in o["pieces"] if not p["z"]]:
        if nm not in pieces:
            probs.append(f"P6 hidden piece {nm} has no mask file")
        elif pieces[nm].any():
            probs.append(f"P6 hidden piece {nm} is not empty ({int(pieces[nm].sum())}px)")
    # P5 inherit: a piece must not contain head/skin that the parent excluded
    for nm in names:
        if pieces[nm].sum() == 0:
            continue
        if (pieces[nm] & ~garment).any():
            probs.append(f"P5 {nm} contains pixels outside the validated garment mask")
    return probs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--only", nargs="*", default=[])
    ap.add_argument("--outdir", default="template/universal-masking")
    ap.add_argument("--sheet", default="template/_qc/pieces-proof.png")
    a = ap.parse_args()
    man = json.load(open(os.path.join(TPL, "pieces.json")))
    os.makedirs(os.path.join(ROOT, a.outdir), exist_ok=True)
    need, built, rej, tiles = [], 0, 0, []
    _unresolved = []
    from PIL import ImageDraw
    for o in man["outfits"]:
        if a.only and o["id"] not in a.only:
            continue
        fp = frame_for(o)
        if not os.path.exists(fp):
            continue
        rgb = np.asarray(Image.open(fp).convert("RGB"), dtype=float)
        # The parent mask is RECOMPUTED here rather than read back from disk, so this
        # tool is idempotent and can never be starved by its own cleanup. (It used to
        # delete the garment mask after splitting, which made every second run quietly
        # process zero outfits - the worst kind of failure, because it looks like success.)
        # It is the same deterministic function mask_blue gates before shipping, so the
        # pieces and the parent cannot drift apart.
        garment, gmet, gprobs = mask_for(rgb)
        if garment is None:
            print(f"  {o['id']:4s} SKIP    parent mask failed: {gprobs}")
            continue
        if gprobs:
            print(f"  {o['id']:4s} SKIP    parent mask rejected: {'; '.join(gprobs)}")
            need.append(o["id"])
            continue
        vis = [p["piece"] for p in o["pieces"] if p["z"]]
        hid = [p["piece"] for p in o["pieces"] if not p["z"]]
        if a.report:
            have = load_anchor(o["id"], vis[0]) if vis else None
            miss = [nm for nm in vis if not os.path.exists(os.path.join(ANCHOR_DIR, f"{o['id']}-{nm}.png"))]
            print(f"  {o['id']:4s} {len(vis)} visible pieces {vis}  "
                  f"{'anchor present' if have is not None else 'NEEDS matte: ' + ','.join(miss)}")
            continue
        if len(vis) <= 1:
            pieces = {vis[0]: garment} if vis else {}
        else:
            # Anchor chain. Each piece in front-to-back order takes its matte
            # intersected with whatever is still unclaimed, so pieces cannot overlap and
            # cannot leak outside the validated garment mask. The LAST visible piece takes
            # the whole remainder, which is what makes the partition gap-free by
            # construction rather than by luck.
            pieces, remain, why = {}, garment, []
            for i, nm in enumerate(vis):
                if i == len(vis) - 1:
                    pieces[nm] = remain
                    break
                anc = load_anchor(o["id"], nm, remain.shape)
                if anc is None:
                    why.append(f"{nm}: no matte")
                    break
                cut = anc & remain
                if cut.sum() < 0.02 * garment.sum():
                    why.append(f"{nm}: matte claims only {int(cut.sum())}px")
                    break
                cut = ndimage.binary_closing(cut, np.ones((5, 5)))
                pieces[nm] = largest(cut, remain) & remain
                remain = remain & ~pieces[nm]
            if why:
                pieces = {}
                _unresolved[:] = why
        if not pieces and len(vis) == 2:
            # seam route for a plain top/bottom split
            if True:
                cands = seam_rows(garment, rgb)
                if cands:
                    y = cands[0][0]
                    up, dn = garment & (np.arange(garment.shape[0])[:, None] <= y), garment & (np.arange(garment.shape[0])[:, None] > y)
                    if up.sum() > 0.025 * garment.sum() and dn.sum() > 0.025 * garment.sum():
                        pieces = {vis[0]: up, vis[1]: dn}
        for nm in hid:
            pieces[nm] = np.zeros_like(garment)
        for nm in vis:
            pieces.setdefault(nm, np.zeros_like(garment))
        if _unresolved:
            probs = [f"not split: " + "; ".join(_unresolved)]
            _unresolved.clear()
        else:
            probs = validate(pieces, garment, rgb, o, vis)
        _unresolved.clear() if not probs else None
        if probs:
            rej += 1
            extra = ""
            print(f"  {o['id']:4s} REJECT  " + "; ".join(probs) + extra)
            need.append(o["id"])
            continue
        for nm, msk in pieces.items():
            Image.fromarray((msk * 255).astype(np.uint8)).save(
                os.path.join(ROOT, a.outdir, f"{o['id']}-{nm}-mask.png"))
        built += 1
        areas = " ".join(f"{nm}={int(pieces[nm].sum())//1000}k" for nm in vis)
        print(f"  {o['id']:4s} OK    {areas}")
        im0 = Image.fromarray(np.clip(rgb, 0, 255).astype(np.uint8)); im0.thumbnail((240, 430))
        ov = np.asarray(im0, dtype=float)
        for i, nm in enumerate(vis):
            c = np.array([(232, 76, 61), (58, 148, 220), (66, 190, 110), (240, 180, 60)][i % 4], float)
            sel = np.asarray(Image.fromarray((pieces[nm] * 255).astype(np.uint8)).resize(
                (ov.shape[1], ov.shape[0]), Image.NEAREST)) > 127
            ov[sel] = (0.45 * c + 0.55 * ov[sel])
        im = Image.fromarray(np.clip(ov, 0, 255).astype(np.uint8))
        d = ImageDraw.Draw(im)
        d.text((3, 3), o["id"] + " " + "+".join(vis), fill=(255, 255, 255))
        tiles.append(im)
    if tiles:
        W = 4
        cw, ch = tiles[0].width, max(t.height for t in tiles)
        rows = (len(tiles) + W - 1) // W
        sheet = Image.new("RGB", (W * (cw + 8) + 8, rows * (ch + 8) + 30), (246, 246, 246))
        dd = ImageDraw.Draw(sheet)
        dd.text((8, 8), "one colour per garment piece - each is its own mask, partitioned with no gap and no overlap",
                fill=(10, 10, 10))
        for i, t in enumerate(tiles):
            r, c = divmod(i, W)
            sheet.paste(t, (8 + c * (cw + 8), 30 + r * (ch + 8)))
        sheet.save(os.path.join(ROOT, a.sheet))
    print(f"\n{built} outfits split into pieces, {rej} rejected")
    if need:
        print("need a matte (or a provable seam): " + " ".join(need))
    return 0 if not rej else 1


if __name__ == "__main__":
    sys.exit(main())
